apiVersion: apps/v1
kind: Deployment
metadata:
  name: g37-lanches-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g37-lanches-api
  template:
    metadata:
      labels:
        app: g37-lanches-api
    spec:
      containers:
        - name: g37-lanches-api
          image: igorramos/g37-lanches-api:production
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: prod
            - name: AUTHORIZER_URL
              value: 'https://o1kfue6x0c.execute-api.us-east-1.amazonaws.com/production/auth'
            - name: POSTGRES_HOST
              value: 'g73-techchallenge-db.cxokeewukuer.us-east-1.rds.amazonaws.com'
            - name: POSTGRES_DB
              value: 'techchallengedb'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
                
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general