apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamo
  template:
    metadata:
      labels:
        app: dynamo
    spec:
      containers:
        - name: dynamo
          image: amazon/dynamodb-local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

