paymentBroker:
  url: https://api.mercadopago.com/instore/orders/qr/seller/collectors/teste/pos/123/qrs
  notificationUrl: https://g37-lanches
  sponsorId: "12345"

paymentRepository:
  table: Payment
  endpoint:

orderEvents:
  topic: order_events
  paymentDestination: orders.payment