name: pipeline payment-ms

on:
  push:
    branches:
      - master
      - pipeline
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch: { }

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: bin

  code-analisys: 
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
        - name: Clone repo
          uses: actions/checkout@v2
              
        - name: Set golang
          uses: actions/setup-go@v2
          with:
            go-version: '1.20'
              
        - name: Run tests
          run: go test -coverprofile=./cov.out ./...

        - name: Install GoSec
          run: | 
              go install github.com/securego/gosec
              echo "Gosec installed at $(which gosec)"
              ls -la $HOME/go/bin/
  
        - name: Run GoSec
          run: |
              $HOME/go/bin/gosec -no-fail -fmt=sonarqube -out report.json ./...
              echo "Gosec completed"
        
        - name: Upload coverage to SonarCloud
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: code-analisys
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image
        run: |
          docker build -t igorramos/g73-techchallenge-payment .
          docker push igorramos/g73-techchallenge-payment      



