name: pipeline payment-ms

on:
  push:
    branches:
      - master
      - pipeline
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...

  code-analisys: 
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
        - name: Clone repo
          uses: actions/checkout@v2
              
        - name: Set golang
          uses: actions/setup-go@v2
          with:
            go-version: '1.20'
              
        - name: Run tests
          run: go test ./... -coverprofile=coverage.out
        
        - name: Upload coverage to SonarCloud
          uses: SonarSource/sonarcloud-github-action@master
          with:
            projectBaseDir: .
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
        - name: Validate SonarCloud quality gate
          uses: SonarSource/sonarcloud-github-action@master
          with:
            args: sonar-quality-gate:wait
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: code-analisys
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image
        run: |
          docker build -t igorramos/g73-techchallenge-payment .
          docker push igorramos/g73-techchallenge-payment      



